openapi: 3.0.1
info:
  title: Template Documetation
  description: 'This is a template for yor server projects.'
  contact:
    email: jose.marmolejos@xennialinnovations.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080
tags:
- name: todo
  description: Everything about your todos
- name: auth
  description: Authentication service